### ISSUE TITLE
panic: none pager occured when pnzr vault view

### ISSUE THREAD

**Issue by rodhiam** [jobtalk/pnzr#88]
When I executed `pnzr vault view`, following error is happened.

```
$ pnzr --version
Build version: unknown
Go version: go1.8.3
Build Date:
Build OS:
$ AWS_REGION=ap-northeast-1 pnzr vault view -profile myprofile pnzr/env.json
panic: none pager

goroutine 1 [running]:
github.com/jobtalk/pnzr/subcmd/vault/view.(*ViewCommand).Run(0xc4200507c0, 0xc4200100f0, 0x3, 0x3, 0x969ae0)
        /go/src/github.com/jobtalk/pnzr/subcmd/vault/view/view.go:125 +0x588
github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42013a180, 0xc4200f3e30, 0x83f7c0, 0xc42013a0c0)
        /go/src/github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli/cli.go:160 +0x18e
github.com/jobtalk/pnzr/subcmd/vault.(*VaultCommand).Run(0xc4200c8d80, 0xc4200100e0, 0x4, 0x4, 0x969dc0)
        /go/src/github.com/jobtalk/pnzr/subcmd/vault/vault.go:44 +0x59
github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42013a0c0, 0xc42012b8c0, 0x94eee2, 0x6)
        /go/src/github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli/cli.go:160 +0x18e
main.main()
        /go/src/github.com/jobtalk/pnzr/main.go:58 +0x1de
```

pnzr stable version happens same error

```
$ curl https://raw.githubusercontent.com/jobtalk/pnzr/master/install.sh | sudo sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1654  100  1654    0     0   3201      0 --:--:-- --:--:-- --:--:--  3205
Downloading pnzr binary from https://github.com/jobtalk/pnzr/releases/download/v1.3.1/pnzr-linux-amd64 to /usr/local/in/pnzr
pnzr installation was successful
$ pnzr --version
Build version: v1.3.1
Go version: go1.9.1
Build Date: Fri Oct 20 08:35:24 UTC 2017
Build OS: Linux
$ AWS_REGION=ap-northeast-1 pnzr vault view -profile myprofile pnzr/env.json
panic: none pager

goroutine 1 [running]:
github.com/jobtalk/pnzr/subcmd/vault/view.(*ViewCommand).Run(0xc4200507c0, 0xc4200100f0, 0x3, 0x3, 0x969ae0)
        /go/src/github.com/jobtalk/pnzr/subcmd/vault/view/view.go:125 +0x588
github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42013a180, 0xc4200f3e30, 0x83f7c0, 0xc42013a0c0$
        /go/src/github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli/cli.go:160 +0x18e
github.com/jobtalk/pnzr/subcmd/vault.(*VaultCommand).Run(0xc4200c8d80, 0xc4200100e0, 0x4, 0x4, 0x969dc0)
        /go/src/github.com/jobtalk/pnzr/subcmd/vault/vault.go:44 +0x59
github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42013a0c0, 0xc42012b8c0, 0x94eee2, 0x6)
        /go/src/github.com/jobtalk/pnzr/vendor/github.com/mitchellh/cli/cli.go:160 +0x18e
main.main()
        /go/src/github.com/jobtalk/pnzr/main.go:58 +0x1de
```

I checked json file is exists (sorry, I can't show all of contents)

```
$ cat pnzr/env.json
{"type":"kms","cipher":"AQICAH..."}
```

OS is `ubuntu 16.04.2 LTS (Xenial Xerus)`

thanks.

**Comment by rodhiam** [comment]
I tried same command on my mac and get other error.
Should I create following error to new issue?

```
-> % AWS_REGION=ap-northeast-1 pnzr vault view -profile myprofile pnzr/env.json
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/ieee0824/cryptex.(*Cryptex).decrypt(0xc420119d28, 0x0, 0x0, 0x0, 0x20, 0x14fdfc0, 0x1565b01)
        /Users/yoan/dev/src/github.com/ieee0824/cryptex/cryptex.go:152 +0x45d
github.com/ieee0824/cryptex.(*Cryptex).View(0xc420119d28, 0xc4200dd0a0, 0x3ba, 0x14905c0)
        /Users/yoan/dev/src/github.com/ieee0824/cryptex/cryptex.go:276 +0x85
github.com/jobtalk/pnzr/subcmd/vault/view.(*ViewCommand).Run(0xc42005c840, 0xc4200100f0, 0x3, 0x3, 0x1581a08)
        /Users/yoan/dev/src/github.com/jobtalk/pnzr/subcmd/vault/view/view.go:124 +0x52f
github.com/mitchellh/cli.(*CLI).Run(0xc4200af2c0, 0xc420119e30, 0x1452130, 0xc4200af040)
        /Users/yoan/dev/src/github.com/mitchellh/cli/cli.go:255 +0x1eb
github.com/jobtalk/pnzr/subcmd/vault.(*VaultCommand).Run(0xc4200dce80, 0xc4200100e0, 0x4, 0x4, 0x1581ae8)
        /Users/yoan/dev/src/github.com/jobtalk/pnzr/subcmd/vault/vault.go:44 +0x59
github.com/mitchellh/cli.(*CLI).Run(0xc4200af040, 0xc4201459e0, 0x1566acc, 0x6)
        /Users/yoan/dev/src/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.main()
        /Users/yoan/dev/src/github.com/jobtalk/pnzr/main.go:58 +0x1de
-> % pnzr --version
Build version: f73ea77
Go version: go1.9.2
Build Date: Sun Nov 19 16:49:05 JST 2017
Build OS: Darwin
```

my mac version is sierra (10.12.6)

thanks

**Comment by ieee0824** [comment]
Please try the following command.
`AWS_REGION=ap-northeast-1 pnzr vault view -v prototype -profile myprofile pnzr/env.json`

**Comment by rodhiam** [comment]
Thanks for your information!! 
I can execute command successfully in ubuntu. (And mac!!)
